#pragma once

#include "esphome/core/component.h"
#include "esphome/components/uart/uart.h"
#include "esphome/components/sensor/sensor.h"
#include "esphome/components/binary_sensor/binary_sensor.h"
#include "esphome/components/text_sensor/text_sensor.h"

#include <vector>
#include <map>
#include <string>
#include <unordered_set>

// Include ESPAltherma's label definition (cloned to component dir at build time)
#include "ESPAltherma/include/labeldef.h"

// Forward declare Converter (defined in converters.h, included in .cpp only)
class Converter;

// labelDefs array (generated by ESPHome codegen)
extern LabelDef labelDefs[];
extern const size_t labelDefs_size;

namespace esphome {
namespace altherma {

// Protocol constants
enum AlthermaProtocol : uint8_t {
  PROTOCOL_I = 'I',  // Newer Daikin protocol
  PROTOCOL_S = 'S',  // Older ROTEX protocol
};

// Serial communication constants
static const uint32_t UART_BAUD_RATE = 9600;
static const uint32_t UART_DATA_BITS = 8;
static const uart::UARTParityOptions UART_PARITY = uart::UART_CONFIG_PARITY_EVEN;
static const uint32_t UART_STOP_BITS = 1;
static const uint32_t SERIAL_TIMEOUT_MS = 300;
static const uint32_t INTER_QUERY_DELAY_MS = 50;

// Buffer sizes
static constexpr size_t RX_BUFFER_SIZE = 64;
static constexpr size_t MAX_COMMAND_SIZE = 4;

// Protocol I command codes
static const uint8_t PROTOCOL_I_CMD_HEADER = 0x03;
static const uint8_t PROTOCOL_I_CMD_PREFIX = 0x40;
static const size_t PROTOCOL_I_CMD_LENGTH = 4;
static const size_t PROTOCOL_I_INITIAL_REPLY_LENGTH = 12;
static const size_t PROTOCOL_I_LENGTH_BYTE_INDEX = 2;
static const size_t PROTOCOL_I_DATA_OFFSET = 3;

// Protocol S command codes
static const uint8_t PROTOCOL_S_CMD_HEADER = 0x02;
static const size_t PROTOCOL_S_CMD_LENGTH = 3;
static const size_t PROTOCOL_S_DATA_OFFSET = 1;

// Error response codes
static const uint8_t ERROR_RESPONSE_BYTE1 = 0x15;
static const uint8_t ERROR_RESPONSE_BYTE2 = 0xEA;

// Protocol S registry-specific reply lengths
static const uint8_t PROTOCOL_S_REG_0x50 = 0x50;
static const uint8_t PROTOCOL_S_REG_0x56 = 0x56;
static const size_t PROTOCOL_S_REG_0x50_LENGTH = 6;
static const size_t PROTOCOL_S_REG_0x56_LENGTH = 4;
static const size_t PROTOCOL_S_DEFAULT_LENGTH = 18;

/** 
 * @brief Main component for Altherma heat pump integration.
 * 
 * This component manages serial communication with Daikin Altherma heat pumps,
 * queries registry values, and publishes data to ESPHome sensors.
 */
class AlthermaComponent : public PollingComponent, public uart::UARTDevice {
 public:
  AlthermaComponent() : converter_(nullptr) {}
  ~AlthermaComponent();

  void setup() override;
  void loop() override;
  void update() override;
  void dump_config() override;
  float get_setup_priority() const override { return setup_priority::DATA; }

  /** @brief Set the protocol to use for communication. */
  void set_protocol(AlthermaProtocol protocol) { this->protocol_ = protocol; }

  /** @brief Register a numeric sensor by label name. */
  void register_sensor(const std::string &label, sensor::Sensor *sensor);
  
  /** @brief Register a binary sensor by label name. */
  void register_binary_sensor(const std::string &label, binary_sensor::BinarySensor *sensor);
  
  /** @brief Register a text sensor by label name. */
  void register_text_sensor(const std::string &label, text_sensor::TextSensor *sensor);

 protected:
  // ==================== CRC & Protocol Helpers ====================
  
  /**
   * @brief Calculate CRC checksum for serial protocol.
   * @param data Data buffer to checksum.
   * @param len Length of data.
   * @return CRC checksum (bitwise NOT of sum).
   */
  uint8_t calculate_crc_(const uint8_t *data, size_t len) const;
  
  /**
   * @brief Get expected reply length for a registry query.
   * @param registry_id Registry ID being queried.
   * @return Expected initial reply length in bytes.
   */
  int get_reply_length_(uint8_t registry_id) const;
  
  // ==================== Command & Response Handling ====================
  
  /**
   * @brief Build protocol command for querying a registry.
   * @param registry_id Registry to query.
   * @param cmd Output buffer for command (must be >= MAX_COMMAND_SIZE).
   * @param cmd_len Output parameter for command length.
   */
  void build_command_(uint8_t registry_id, uint8_t *cmd, size_t &cmd_len) const;
  
  /**
   * @brief Read response from serial with timeout.
   * @param buffer Buffer to store response.
   * @param len Input: expected length, Output: actual bytes read.
   * @param start_time Timestamp when command was sent.
   * @return true if response received, false on timeout.
   */
  bool read_response_(uint8_t *buffer, size_t &len, uint32_t start_time);
  
  /**
   * @brief Validate response data (CRC check).
   * @param buffer Response buffer.
   * @param len Response length.
   * @param registry_id Registry ID (for error logging).
   * @return true if valid, false on CRC error.
   */
  bool validate_response_(const uint8_t *buffer, size_t len, uint8_t registry_id) const;
  
  /**
   * @brief Query a heat pump registry via serial.
   * @param registry_id Registry ID to query (0x00-0xFF).
   * @param buffer Buffer to store response.
   * @param len Output parameter for response length.
   * @return true if query successful, false on timeout/error.
   */
  bool query_registry_(uint8_t registry_id, uint8_t *buffer, size_t &len);
  
  /**
   * @brief Build list of unique registry IDs from labelDefs.
   * 
   * Uses O(n) algorithm with std::unordered_set for efficient deduplication.
   */
  void build_registry_list_();
  
  // ==================== Data Publishing ====================
  
  /** @brief Process registry data and publish to all registered sensors. */
  void publish_values_();
  
  /**
   * @brief Parse numeric value from converter output string.
   * @param str String to parse.
   * @param value Output parameter for parsed value.
   * @return true if parsing successful, false otherwise.
   */
  bool parse_numeric_value_(const char *str, float &value) const;
  
  /**
   * @brief Publish value to a numeric sensor if registered.
   * @param label Sensor label.
   * @param value String value from converter.
   */
  void publish_sensor_(const char *label, const char *value);
  
  /**
   * @brief Publish value to a binary sensor if registered.
   * @param label Sensor label.
   * @param value String value from converter.
   */
  void publish_binary_sensor_(const char *label, const char *value);
  
  /**
   * @brief Publish value to a text sensor if registered.
   * @param label Sensor label.
   * @param value String value from converter.
   */
  void publish_text_sensor_(const char *label, const char *value);
  
  /**
   * @brief Check if converter is initialized.
   * @return true if converter is ready, false otherwise.
   */
  bool is_converter_ready_() const { return this->converter_ != nullptr; }

  // Configuration
  AlthermaProtocol protocol_{PROTOCOL_I};
  
  // Converter instance from ESPAltherma (instantiated in cpp)
  Converter *converter_;
  
  // Registries to query (deduplicated list)
  std::vector<uint8_t> unique_registries_;
  
  // Registered sensors (keyed by label)
  std::map<std::string, sensor::Sensor *> sensors_;
  std::map<std::string, binary_sensor::BinarySensor *> binary_sensors_;
  std::map<std::string, text_sensor::TextSensor *> text_sensors_;
  
  // State
  bool initialized_{false};
  uint8_t rx_buffer_[RX_BUFFER_SIZE];
};

}  // namespace altherma
}  // namespace esphome
